version: '3.8'

services:
  apicatalog:
    container_name: apicatalog
    build:
      context: .
      dockerfile: HW_6_2/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:5000
    depends_on:
        - postgres
    ports:
        - 5000:5000

  pgadmin4:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
        - PGADMIN_DEFAULT_EMAIL=user@mail.com
        - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
        - postgres
    ports:
        - 8001:80

  postgres:
    container_name: postgres
    image: postgres
    environment:
        - POSTGRES_PASSWORD=postgrespw
    ports:
        - 5433:5432

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
        - 80:80
    restart: always

networks:    
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.4/24
          gateway: 192.168.0.4