version: '3.8'

services:
  api.catalog:
    container_name: api.catalog
    build:
      context: .
      dockerfile: HW_6_4/Catalog/Catalog.Host/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:5000
    depends_on:
        - postgres
    ports:
        - 5000:5000

  web.client:
    container_name: web.client
    build:
      context: .
      dockerfile: HW_6_4/Web/EShop/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:5001
        - ApiUrl=http://localhost:5000/api/v1/
    depends_on:
        - api.catalog
    ports:
        - 5001:5001

  pgadmin4:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
        - PGADMIN_DEFAULT_EMAIL=user@mail.com
        - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
        - postgres
    ports:
        - 8001:80

  postgres:
    container_name: postgres
    image: postgres
    environment:
        - POSTGRES_PASSWORD=postgrespw
    ports:
        - 5433:5432

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
        - 80:80
    restart: always
    volumes:
      - ./HW_6_4/Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
      - ./HW_6_4/Proxy/assets:/var/www/assets

networks:    
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.4/24
          gateway: 192.168.0.4