version: '3.8'

services:
  catalog.api:
    container_name: catalog.api
    build:
      context: .
      dockerfile: HW_6_1/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000
    ports:
      - 5000:5000
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    restart: always

networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.4/24
          gateway: 192.168.0.4